version: '3.8'
services:
  frontend:
    container_name: frontend
    platform: linux/x86_64
    build: ./frontend
    ports:
      - 3000:5173
    working_dir: /frontend
    volumes:
      - ./frontend/src:/frontend/src
    depends_on:
      - backend
  backend:
    container_name: backend
    platform: linux/x86_64
    build: ./backend
    ports:
      - 3001:3001
    working_dir: /backend
    volumes:
      - ./backend/src:/backend/src
    depends_on:
      - db
    environment:
      - JWT_SECRET=sharenergy_secret_key
  db:
    image: mongo
    container_name: db
    platform: linux/x86_64
    ports:
      - 3002:3002
    environment:
      - MONGO_ROOT_USERNAME=root
      - MONGO_ROOT_PASSWORD=password
      - MONGO_DATABASE=users
    restart: 'always'